### PR TITLE
Gift Amachree

### PR DESCRIPTION
**Pull request by jen67**
I added some contents to the html

### CODE REVIEW

**Review by jen67 — COMMENTED** [review]
I followed the instructions

**Comment by jen67** [comment]
Please I don't know why I cannot merge. I need help please

**Comment by FernandoHoyos** [comment]
Hola, me pasa lo mismo y he modificado el mensaje, pero sigo sin ser aprobado :(

**Comment by jen67** [comment]
Hola..., supongo que es un problema general.

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not add outside links :)

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not add outside links :)

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
