### PR TITLE
Thanks for w3schools-tutorial from Kevin

### PR DESCRIPTION
**Pull request by kevine-22**
Add one Taiwan scenic photo and leave message in public guestbook

### CODE REVIEW

**Comment by kevine-22** [comment]
Thanks for this tutorial. This looks good.

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :) (don't add extra files)

**Comment by kevine-22** [comment]
> Please keep your changes contained to the specified area in index.html :) (don't add extra files)
Sir, Thanks, I had revised them, please review the issue again. 
Sincerely,
Kevin

**Comment by kevine-22** [comment]
Sir,  Thanks,  This branch has no conflicts with the base branch.

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Review by w3schools-test — APPROVED** [review]

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please remove changes from .gitignore

**Comment by kevine-22** [comment]
> Please remove changes from .gitignore

Sir, Thanks. I remove the changes.

**Comment by kevine-22** [comment]
> Please keep your changes contained to the specified area in index.html :)

Sir, Thanks, I keep my changes contained to the specified area in index.html. Please review it.

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
