### PR TITLE
add a dummy file for testing

### PR DESCRIPTION
**Pull request by SaboorAhm7e**

### CODE REVIEW

**Comment by SaboorAhm7e** [comment]
just add a file

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep changes contained to the index.html file :)

**Review by MOUADAKROUBI — APPROVED** [review]
approve your code

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep changes contained to the index.html file :)

**Pull request closed without merging**
