### PR TITLE
changed the readme to add some text

### PR DESCRIPTION
**Pull request by Philomoime**

### CODE REVIEW

**Comment by Philomoime** [comment]
OK good, I now comment on the changes and will merge.

**Comment by Nvegs** [comment]
you were only asked to make changes to the HTML file nothing else. Do that ASAP

**Comment by Philomoime** [comment]
OK thanks for the reply

**Comment by Nvegs** [comment]
Happy Learning

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep changes contained to the index.html file :)

**Pull request closed without merging**
