### PR TITLE
New Message added to index.html

### PR DESCRIPTION
**Pull request by gabowagner**
New Message added to index.html

Thank you W3Schools.com!

### CODE REVIEW

**Comment by gabowagner** [comment]
Thanks!

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Comment by gabowagner** [comment]
> Please keep your changes contained to the specified area in index.html :)

Changes Made

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Pull request closed without merging**
