### PR TITLE
Hisham Eissa added message

### PR DESCRIPTION
**Pull request by HishamEissa**
Added Message to index
Hisham Eissa

### CODE REVIEW

**Comment by HishamEissa** [comment]
approving my message
Hisham Eissa

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not change or remove content added by others :)

**Comment by HishamEissa** [comment]
Was I able to do a change to the pull request ?

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not change or remove content added by others :)

**Pull request closed without merging**
