### PR TITLE
Message from Farhan Reza

### PR DESCRIPTION
**Pull request by farhan7reza7**
i have added my message by adding my introduction and my feedback for this  public guestbook project.

### CODE REVIEW

**Comment by farhan7reza7** [comment]
hoping for knowing update about my pull request...

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not change or remove content added by others :)

**Comment by farhan7reza7** [comment]
yes, now i have made changes in my message as per the changes requested...

**Review by farhan7reza7 — COMMENTED** [review]
in split of changes, i found this time my codes is not disturbing others codes

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
