### PR TITLE
added my contribution to index.html

### PR DESCRIPTION
**Pull request by wloerakving**

### CODE REVIEW

**Comment by wloerakving** [comment]
Added a line to index.html

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Comment by wloerakving** [comment]
Update index.html

**Comment by wloerakving** [comment]
Added neat changes.

**Comment by wloerakving** [comment]
Updated changes.

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Looks good, just remove the "trial.html" file.

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
