### PR TITLE
Added Note-Taran

### PR DESCRIPTION
**Pull request by Taran1508**

### CODE REVIEW

**Comment by Taran1508** [comment]
added taran's note

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not add outside links :)

**Review by w3schools-test — CHANGES_REQUESTED** [review]
There are still links in the second section, and please remove the changes from .gitignore

**Comment by Taran1508** [comment]
links in the second section, and  the changes from .gitignore are removed

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
