### PR TITLE
New message for Ghasus

### PR DESCRIPTION
**Pull request by Ghasus**
I made changes to index.html in accordance with your recommendations. Thanx.

### CODE REVIEW

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Comment by Ghasus** [comment]
Thanx for your comment. I'm not aware of any changes outside the specified area.

**Comment by w3schools-test** [comment]
You are requesting to delete .gitignore file

**Comment by Ghasus** [comment]
OK, my mistake. I thought I am deleting the one I had created. 
So, is it possible to accept only the changes I had made to index.html or should I close this request and submit a new one?

**Pull request closed without merging**
