### PR TITLE
Changes the index.html

### PR DESCRIPTION
**Pull request by hariysu**
I changed the index.html. Add explanations about git tutorial on w3schools.

### CODE REVIEW

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not remove content added by others :)

**Review by hariysu — COMMENTED** [review]
I did not remove any comment of others

**Comment by w3schools-test** [comment]
You removed the 

`    <!-- Insert your message below here -->`

line

**Review by w3schools-test — APPROVED** [review]

**Comment by hariysu** [comment]
I added message line to index.html.

**Pull request merged**
