### PR TITLE
Added motivational message to index.html

### PR DESCRIPTION
**Pull request by carlitoe**
Added motivational message from a book I am currently reading to index.html

### CODE REVIEW

**Comment by carlitoe** [comment]
Approving my own changes to spread some love

**Review by carlitoe — COMMENTED** [review]
only added <br>

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Review by Ebrahim-Gamal-77 — CHANGES_REQUESTED** [review]
Bro I think you need to read main repo instructions , they said that there is a specified place to put your message.

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
