### PR TITLE
Added my Guestbook entry in w3schools-test

### PR DESCRIPTION
**Pull request by Kazeshini94**
Added myself as last guestbook entry :) thanks for your amazing guides and tools :)

### CODE REVIEW

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not rewrite content added by others :)

**Comment by Kazeshini94** [comment]
oh that was a mistake on my part. gonna retry to add myself without destroying existing code xD

**Comment by Kazeshini94** [comment]
hopefully got it right this time :) and thanks for your effort and time mate :)

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Hi Kaz! There is still a lot of changes to the existing code. Ideally the difference between the original and your commit should only be the lines you added. No new spacing etc. of the original :)

**Pull request closed without merging**
