### PR TITLE
a simple thank you message in kurdish

### PR DESCRIPTION
**Pull request by hazhir00**

### CODE REVIEW

**Comment by navneet11121992** [comment]
can u explain what is kurdish

**Comment by navneet11121992** [comment]
> i added a p tag in your html file and wrote a thank you message in kurdish :*

can u explain what is kurdish please

**Review by w3schools-test — APPROVED** [review]

**Comment by hazhir00** [comment]
> can u explain what is kurdish

kurdish is a language.

**Comment by navneet11121992** [comment]
what type of language is it?

**Comment by hazhir00** [comment]
you can read about it here: https://en.wikipedia.org/wiki/Kurdish_language

**Comment by navneet11121992** [comment]
can u make my profile summary in kurdish?

**Comment by hazhir00** [comment]
I am new to GitHub and not sure what your profile summary is, so I can translate it for you. Can you show me?

**Comment by navneet11121992** [comment]
thank you for your support and cooperation.

**Pull request merged**
