### PR TITLE
My name is added

### PR DESCRIPTION
**Pull request by RajMaity**

### CODE REVIEW

**Comment by RajMaity** [comment]
I added my name and expressed thanks to w3school for the tutorial

**Comment by RajMaity** [comment]
Edited the index.html file

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :) (Specifically the "I" character on line 42)

**Comment by RajMaity** [comment]
Removed the 'I' on line 42.

**Review by w3schools-test — APPROVED** [review]

**Pull request merged**
