### PR TITLE
update my comment in index.html

### PR DESCRIPTION
**Pull request by justicar1911**
i input my comment in the html file

### CODE REVIEW

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please do not change or remove content added by others :)

**Comment by justicar1911** [comment]
I have resolve the conflict

**Comment by emax-77** [comment]
comment (not) updated :)

**Review by w3schools-test — CHANGES_REQUESTED** [review]
You are still changing a lot of spaces and indentations for content added by others. Please make the changes to your specific message only :)

**Pull request closed without merging**
