### PR TITLE
w3school 1st update my site

### PR DESCRIPTION
**Pull request by lingarajtechhub**

### CODE REVIEW

**Comment by lingarajtechhub** [comment]
I am tested veryfy the code

**Review by lingarajtechhub — COMMENTED** [review]
I am add one section on index.html

**Comment by lingarajtechhub** [comment]
add new section on index.html

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Pull request closed without merging**
