### PR TITLE
Örkény István one minute story in hungarian and english

### PR DESCRIPTION
**Pull request by viragdavidcsanad**
Örkény István quote was added to index.html file.

### CODE REVIEW

**Review by w3schools-test — CHANGES_REQUESTED** [review]
Please keep your changes contained to the specified area in index.html :)

**Comment by viragdavidcsanad** [comment]
> Örkény István quote was added to index.html file.
> Please keep your changes contained to the specified area in index.html :)
> Hello! Sorry! I fixed the message, I hope, it will be OK.

**Comment by viragdavidcsanad** [comment]
I fixed the message, and added an English translation. I hope this is already acceptable.

**Comment by viragdavidcsanad** [comment]
I solved the conflict. I fixed the message, and added an English translation. I hope this is already acceptable.

**Comment by viragdavidcsanad** [comment]
> Please keep your changes contained to the specified area in index.html :)

I solved the conflict. I fixed the message, and added an English translation. I hope this is already acceptable.

**Pull request closed without merging**
